pipeline:
  identifier: Build_FSou1_ttcom_1777260329654
  name: Build ttcom
  orgIdentifier: default
  projectIdentifier: ttcom
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1777260289768
        repoName: FSou1/ttcom
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Node
                  identifier: installnode
                  spec:
                    shell: Sh
                    envVariables:
                      NODE_VERSION: 18.16.0
                    command: |-
                      mkdir $HOME/nodejs
                      curl -L https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz | tar xJ -C $HOME/nodejs
                      export PATH=$HOME/nodejs/node-v${NODE_VERSION}-linux-x64/bin:$PATH
                      node -v
                      npm -v
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: |-
                      node -v
                      npm -v
                      npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: lint
                  name: lint
                  spec:
                    command: npm run lint
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    command: npm run build
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
